/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.minipos;

import javax.swing.JOptionPane;

/**
 *
 * @author OBUZIETTER3000
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        openTillMenuItem = new javax.swing.JMenuItem();
        closeTillMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        salesMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        usersMenuItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        userResetMenuItem = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINI POS V1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jMenu1.setText("Dashboard");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Front Office");

        jMenu5.setText("Till Operations");

        openTillMenuItem.setText("Open Till");
        openTillMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTillMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(openTillMenuItem);

        closeTillMenuItem.setText("Close Till");
        closeTillMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTillMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(closeTillMenuItem);

        jMenu2.add(jMenu5);

        jMenuItem2.setText("Cash Pick-up");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        salesMenuItem.setText("Sales");
        salesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(salesMenuItem);

        jMenuItem4.setText("Sales History");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Back Office");

        jMenuItem5.setText("Customers");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Suppliers");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Inventory");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Accounts");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Reports");
        jMenu3.add(jMenuItem9);

        jMenuItem11.setText("Expenses");
        jMenu3.add(jMenuItem11);

        usersMenuItem.setText("Users");
        usersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(usersMenuItem);

        jMenu6.setText("Returns");

        jMenuItem1.setText("Inwards");
        jMenu6.add(jMenuItem1);

        jMenuItem18.setText("Outwards");
        jMenu6.add(jMenuItem18);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utility");

        userResetMenuItem.setText("User Reset");
        userResetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userResetMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(userResetMenuItem);

        jMenuItem14.setText("Help & Support");
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Company Details");
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void salesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesMenuItemActionPerformed
        desktopPane.removeAll();
        SalesInternalFrame salesInternalFrame = new SalesInternalFrame();
        salesInternalFrame.setVisible(true); // Make the internal frame visible
        desktopPane.add(salesInternalFrame); // Add to desktop pane
        desktopPane.revalidate(); // Revalidate to apply changes
        desktopPane.repaint(); // Repaint to update the display
    }//GEN-LAST:event_salesMenuItemActionPerformed

    private void userResetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userResetMenuItemActionPerformed
        desktopPane.removeAll();
        UserResetInternalFrame userResetInternalFrame = new UserResetInternalFrame();
        userResetInternalFrame.setVisible(true); // Make the internal frame visible
        desktopPane.add(userResetInternalFrame); // Add to desktop pane
        desktopPane.revalidate(); // Revalidate to apply changes
        desktopPane.repaint(); // Repaint to update the display

    }//GEN-LAST:event_userResetMenuItemActionPerformed

    private void usersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMenuItemActionPerformed
        desktopPane.removeAll();
        UsersInternalFrame usersInternalFrame = new UsersInternalFrame();
        usersInternalFrame.setVisible(true); // Make the internal frame visible
        desktopPane.add(usersInternalFrame); // Add to desktop pane
        desktopPane.revalidate(); // Revalidate to apply changes
        desktopPane.repaint(); // Repaint to update the display
    }//GEN-LAST:event_usersMenuItemActionPerformed

    private void openTillMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTillMenuItemActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Till Opened!");
        
    }//GEN-LAST:event_openTillMenuItemActionPerformed

    private void closeTillMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTillMenuItemActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Till Closed!");
    }//GEN-LAST:event_closeTillMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeTillMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem openTillMenuItem;
    private javax.swing.JMenuItem salesMenuItem;
    private javax.swing.JMenuItem userResetMenuItem;
    private javax.swing.JMenuItem usersMenuItem;
    // End of variables declaration//GEN-END:variables
}
