/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.minipos;

import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OBUZIETTER3000
 */
public class UsersInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsersInternalFrame
     */
    public UsersInternalFrame() {
        initComponents();
        
        getAllUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPopupMenu = new javax.swing.JPopupMenu();
        editUserMenuItem = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        id_tf = new javax.swing.JTextField();
        first_name_tf = new javax.swing.JTextField();
        last_name_tf = new javax.swing.JTextField();
        username_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        till_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        new_user_btn = new javax.swing.JButton();
        active_combo = new javax.swing.JComboBox<>();

        editUserMenuItem.setText("Edit User");
        editUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserMenuItemActionPerformed(evt);
            }
        });
        userPopupMenu.add(editUserMenuItem);

        setClosable(true);
        setIconifiable(true);
        setTitle("User Management");

        users_table.setBackground(new java.awt.Color(0, 0, 0));
        users_table.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        users_table.setForeground(new java.awt.Color(255, 255, 0));
        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Username", "Active", "Till Open"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        users_table.setComponentPopupMenu(userPopupMenu);
        users_table.setRowHeight(30);
        users_table.setSelectionBackground(new java.awt.Color(255, 255, 0));
        users_table.setSelectionForeground(new java.awt.Color(255, 51, 0));
        users_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                users_tableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(users_table);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setText("Search User");
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        id_tf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        id_tf.setEnabled(false);

        first_name_tf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        last_name_tf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        username_tf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        password_tf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("LAST NAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("USERNAME");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("PASSWORD");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("ACTIVE");

        till_combo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        till_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLOSED", "OPEN" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("TILL");

        update_btn.setBackground(new java.awt.Color(0, 255, 255));
        update_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        new_user_btn.setBackground(new java.awt.Color(102, 102, 255));
        new_user_btn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        new_user_btn.setText("CREATE USER");
        new_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_user_btnActionPerformed(evt);
            }
        });

        active_combo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        active_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(first_name_tf)
                    .addComponent(id_tf)
                    .addComponent(active_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(last_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(till_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(new_user_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(new_user_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(till_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(active_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_user_btnActionPerformed
        NewUserFrame newUserFrame = new NewUserFrame();
        newUserFrame.setVisible(true);
    }//GEN-LAST:event_new_user_btnActionPerformed

    private void users_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_tableMousePressed
        if (evt.getButton() == MouseEvent.BUTTON3) { // Right mouse button
            int row = users_table.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                users_table.setRowSelectionInterval(row, row); // Select the row
            }
        }
    }//GEN-LAST:event_users_tableMousePressed

    private void editUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserMenuItemActionPerformed
        
        User user = new User();
        
        User foundUser = user.readUser(users_table.getValueAt(users_table.getSelectedRow(), 2).toString());
        id_tf.setText(foundUser.getUserId());        
        
        first_name_tf.setText(users_table.getValueAt(users_table.getSelectedRow(), 0).toString());
        last_name_tf.setText(users_table.getValueAt(users_table.getSelectedRow(), 1).toString());
        username_tf.setText(users_table.getValueAt(users_table.getSelectedRow(), 2).toString());
        
        String isUserActive = users_table.getValueAt(users_table.getSelectedRow(), 3).toString();
        switch (isUserActive) {
            case "true" ->
                active_combo.setSelectedIndex(1);
            case "false" ->
                active_combo.setSelectedIndex(0);
        }
        String isTillOpen = users_table.getValueAt(users_table.getSelectedRow(), 4).toString();
        switch (isTillOpen) {
            case "true" ->
                till_combo.setSelectedIndex(1);
            case "false" ->
                till_combo.setSelectedIndex(0);
        }
        

    }//GEN-LAST:event_editUserMenuItemActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        User user = new User();
        user.setUserId(id_tf.getText());
        user.setFirstName(first_name_tf.getText());
        user.setLastName(last_name_tf.getText());
        user.setUsername(username_tf.getText());
        user.setPassword(password_tf.getText());
        
        int isUserActive = active_combo.getSelectedIndex();
        switch (isUserActive) {
            case 0 ->
                user.setActive(false);
            case 1 ->
                user.setActive(true);
        }
        int isTillOpen = till_combo.getSelectedIndex();
        switch (isTillOpen) {
            case 0 ->
                user.setTillOpen(false);
            case 1 ->
                user.setTillOpen(true);
        }
        user.updateUser();
        
        getAllUsers();
        
        id_tf.setText(null);
        first_name_tf.setText(null);
        last_name_tf.setText(null);
        username_tf.setText(null);
        password_tf.setText(null);
    }//GEN-LAST:event_update_btnActionPerformed
    
    private void getAllUsers() {
        
        DefaultTableModel model = (DefaultTableModel) users_table.getModel();
        User userHandler = new User();
        List<User> allUsers = userHandler.getAllUsers();
        for (User user : allUsers) {
            
            Object[] userData = {user.getFirstName(), user.getLastName(), user.getUsername(), user.isActive(), user.isTillOpen()};
            System.out.println("Username: " + user.getUsername());
            System.out.println("First Name: " + user.getFirstName());
            System.out.println("Last Name: " + user.getLastName());
            System.out.println("Active: " + user.isActive());
            System.out.println("Till Open: " + user.isTillOpen());
            System.out.println();
            model.addRow(userData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> active_combo;
    private javax.swing.JMenuItem editUserMenuItem;
    private javax.swing.JTextField first_name_tf;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField last_name_tf;
    private javax.swing.JButton new_user_btn;
    private javax.swing.JTextField password_tf;
    private javax.swing.JComboBox<String> till_combo;
    private javax.swing.JButton update_btn;
    private javax.swing.JPopupMenu userPopupMenu;
    private javax.swing.JTextField username_tf;
    private javax.swing.JTable users_table;
    // End of variables declaration//GEN-END:variables
}
